/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace CrossChainRouter {
  export type CrossChainMessageStruct = {
    messageId: BytesLike;
    sourceChainId: BigNumberish;
    destinationChainId: BigNumberish;
    sender: AddressLike;
    recipient: AddressLike;
    token: AddressLike;
    amount: BigNumberish;
    data: BytesLike;
    nonce: BigNumberish;
    executed: boolean;
    timestamp: BigNumberish;
  };

  export type CrossChainMessageStructOutput = [
    messageId: string,
    sourceChainId: bigint,
    destinationChainId: bigint,
    sender: string,
    recipient: string,
    token: string,
    amount: bigint,
    data: string,
    nonce: bigint,
    executed: boolean,
    timestamp: bigint
  ] & {
    messageId: string;
    sourceChainId: bigint;
    destinationChainId: bigint;
    sender: string;
    recipient: string;
    token: string;
    amount: bigint;
    data: string;
    nonce: bigint;
    executed: boolean;
    timestamp: bigint;
  };
}

export interface CrossChainRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DENOMINATOR"
      | "bridgeFee"
      | "chainTokenMapping"
      | "emergencyHalt"
      | "executeTransfer"
      | "getMessage"
      | "getMinReceived"
      | "initiateTransfer"
      | "messages"
      | "nonces"
      | "owner"
      | "paused"
      | "renounceOwnership"
      | "resume"
      | "setBridgeFee"
      | "setChainSupport"
      | "setSlippageTolerance"
      | "setTokenMapping"
      | "slippageTolerance"
      | "supportedChains"
      | "transferOwnership"
      | "withdrawFees"
      | "withdrawTokens"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ChainSupportUpdated"
      | "CrossChainTransferExecuted"
      | "CrossChainTransferInitiated"
      | "EmergencyHalted"
      | "FeeUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "Resumed"
      | "TokenMappingUpdated"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BPS_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "bridgeFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "chainTokenMapping",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyHalt",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeTransfer",
    values: [BytesLike, AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMessage",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMinReceived",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initiateTransfer",
    values: [BigNumberish, AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "messages", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "nonces", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "resume", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setBridgeFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setChainSupport",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setSlippageTolerance",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenMapping",
    values: [BigNumberish, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "slippageTolerance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportedChains",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawTokens",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "BPS_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bridgeFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "chainTokenMapping",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyHalt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMessage", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMinReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initiateTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "messages", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nonces", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resume", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setBridgeFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setChainSupport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSlippageTolerance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenMapping",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "slippageTolerance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportedChains",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawTokens",
    data: BytesLike
  ): Result;
}

export namespace ChainSupportUpdatedEvent {
  export type InputTuple = [chainId: BigNumberish, supported: boolean];
  export type OutputTuple = [chainId: bigint, supported: boolean];
  export interface OutputObject {
    chainId: bigint;
    supported: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CrossChainTransferExecutedEvent {
  export type InputTuple = [
    messageId: BytesLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    messageId: string,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    messageId: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CrossChainTransferInitiatedEvent {
  export type InputTuple = [
    messageId: BytesLike,
    sourceChain: BigNumberish,
    destinationChain: BigNumberish,
    sender: AddressLike,
    recipient: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    messageId: string,
    sourceChain: bigint,
    destinationChain: bigint,
    sender: string,
    recipient: string,
    token: string,
    amount: bigint
  ];
  export interface OutputObject {
    messageId: string;
    sourceChain: bigint;
    destinationChain: bigint;
    sender: string;
    recipient: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyHaltedEvent {
  export type InputTuple = [by: AddressLike];
  export type OutputTuple = [by: string];
  export interface OutputObject {
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeUpdatedEvent {
  export type InputTuple = [newFee: BigNumberish];
  export type OutputTuple = [newFee: bigint];
  export interface OutputObject {
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResumedEvent {
  export type InputTuple = [by: AddressLike];
  export type OutputTuple = [by: string];
  export interface OutputObject {
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenMappingUpdatedEvent {
  export type InputTuple = [
    chainId: BigNumberish,
    localToken: AddressLike,
    remoteToken: AddressLike
  ];
  export type OutputTuple = [
    chainId: bigint,
    localToken: string,
    remoteToken: string
  ];
  export interface OutputObject {
    chainId: bigint;
    localToken: string;
    remoteToken: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CrossChainRouter extends BaseContract {
  connect(runner?: ContractRunner | null): CrossChainRouter;
  waitForDeployment(): Promise<this>;

  interface: CrossChainRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  bridgeFee: TypedContractMethod<[], [bigint], "view">;

  chainTokenMapping: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [string],
    "view"
  >;

  emergencyHalt: TypedContractMethod<[], [void], "nonpayable">;

  executeTransfer: TypedContractMethod<
    [
      messageId: BytesLike,
      recipient: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      minReceived: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getMessage: TypedContractMethod<
    [messageId: BytesLike],
    [CrossChainRouter.CrossChainMessageStructOutput],
    "view"
  >;

  getMinReceived: TypedContractMethod<[amount: BigNumberish], [bigint], "view">;

  initiateTransfer: TypedContractMethod<
    [
      destinationChainId: BigNumberish,
      recipient: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      minReceived: BigNumberish
    ],
    [void],
    "payable"
  >;

  messages: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        bigint,
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        bigint,
        boolean,
        bigint
      ] & {
        messageId: string;
        sourceChainId: bigint;
        destinationChainId: bigint;
        sender: string;
        recipient: string;
        token: string;
        amount: bigint;
        data: string;
        nonce: bigint;
        executed: boolean;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  nonces: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resume: TypedContractMethod<[], [void], "nonpayable">;

  setBridgeFee: TypedContractMethod<
    [newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setChainSupport: TypedContractMethod<
    [chainId: BigNumberish, supported: boolean],
    [void],
    "nonpayable"
  >;

  setSlippageTolerance: TypedContractMethod<
    [tolerance: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTokenMapping: TypedContractMethod<
    [chainId: BigNumberish, localToken: AddressLike, remoteToken: AddressLike],
    [void],
    "nonpayable"
  >;

  slippageTolerance: TypedContractMethod<[], [bigint], "view">;

  supportedChains: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawFees: TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawTokens: TypedContractMethod<
    [token: AddressLike, recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "bridgeFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "chainTokenMapping"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "emergencyHalt"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeTransfer"
  ): TypedContractMethod<
    [
      messageId: BytesLike,
      recipient: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      minReceived: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getMessage"
  ): TypedContractMethod<
    [messageId: BytesLike],
    [CrossChainRouter.CrossChainMessageStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMinReceived"
  ): TypedContractMethod<[amount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "initiateTransfer"
  ): TypedContractMethod<
    [
      destinationChainId: BigNumberish,
      recipient: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      minReceived: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "messages"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        bigint,
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        bigint,
        boolean,
        bigint
      ] & {
        messageId: string;
        sourceChainId: bigint;
        destinationChainId: bigint;
        sender: string;
        recipient: string;
        token: string;
        amount: bigint;
        data: string;
        nonce: bigint;
        executed: boolean;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nonces"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resume"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setBridgeFee"
  ): TypedContractMethod<[newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setChainSupport"
  ): TypedContractMethod<
    [chainId: BigNumberish, supported: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSlippageTolerance"
  ): TypedContractMethod<[tolerance: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTokenMapping"
  ): TypedContractMethod<
    [chainId: BigNumberish, localToken: AddressLike, remoteToken: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "slippageTolerance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "supportedChains"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawTokens"
  ): TypedContractMethod<
    [token: AddressLike, recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ChainSupportUpdated"
  ): TypedContractEvent<
    ChainSupportUpdatedEvent.InputTuple,
    ChainSupportUpdatedEvent.OutputTuple,
    ChainSupportUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CrossChainTransferExecuted"
  ): TypedContractEvent<
    CrossChainTransferExecutedEvent.InputTuple,
    CrossChainTransferExecutedEvent.OutputTuple,
    CrossChainTransferExecutedEvent.OutputObject
  >;
  getEvent(
    key: "CrossChainTransferInitiated"
  ): TypedContractEvent<
    CrossChainTransferInitiatedEvent.InputTuple,
    CrossChainTransferInitiatedEvent.OutputTuple,
    CrossChainTransferInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyHalted"
  ): TypedContractEvent<
    EmergencyHaltedEvent.InputTuple,
    EmergencyHaltedEvent.OutputTuple,
    EmergencyHaltedEvent.OutputObject
  >;
  getEvent(
    key: "FeeUpdated"
  ): TypedContractEvent<
    FeeUpdatedEvent.InputTuple,
    FeeUpdatedEvent.OutputTuple,
    FeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "Resumed"
  ): TypedContractEvent<
    ResumedEvent.InputTuple,
    ResumedEvent.OutputTuple,
    ResumedEvent.OutputObject
  >;
  getEvent(
    key: "TokenMappingUpdated"
  ): TypedContractEvent<
    TokenMappingUpdatedEvent.InputTuple,
    TokenMappingUpdatedEvent.OutputTuple,
    TokenMappingUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "ChainSupportUpdated(uint256,bool)": TypedContractEvent<
      ChainSupportUpdatedEvent.InputTuple,
      ChainSupportUpdatedEvent.OutputTuple,
      ChainSupportUpdatedEvent.OutputObject
    >;
    ChainSupportUpdated: TypedContractEvent<
      ChainSupportUpdatedEvent.InputTuple,
      ChainSupportUpdatedEvent.OutputTuple,
      ChainSupportUpdatedEvent.OutputObject
    >;

    "CrossChainTransferExecuted(bytes32,address,uint256)": TypedContractEvent<
      CrossChainTransferExecutedEvent.InputTuple,
      CrossChainTransferExecutedEvent.OutputTuple,
      CrossChainTransferExecutedEvent.OutputObject
    >;
    CrossChainTransferExecuted: TypedContractEvent<
      CrossChainTransferExecutedEvent.InputTuple,
      CrossChainTransferExecutedEvent.OutputTuple,
      CrossChainTransferExecutedEvent.OutputObject
    >;

    "CrossChainTransferInitiated(bytes32,uint256,uint256,address,address,address,uint256)": TypedContractEvent<
      CrossChainTransferInitiatedEvent.InputTuple,
      CrossChainTransferInitiatedEvent.OutputTuple,
      CrossChainTransferInitiatedEvent.OutputObject
    >;
    CrossChainTransferInitiated: TypedContractEvent<
      CrossChainTransferInitiatedEvent.InputTuple,
      CrossChainTransferInitiatedEvent.OutputTuple,
      CrossChainTransferInitiatedEvent.OutputObject
    >;

    "EmergencyHalted(address)": TypedContractEvent<
      EmergencyHaltedEvent.InputTuple,
      EmergencyHaltedEvent.OutputTuple,
      EmergencyHaltedEvent.OutputObject
    >;
    EmergencyHalted: TypedContractEvent<
      EmergencyHaltedEvent.InputTuple,
      EmergencyHaltedEvent.OutputTuple,
      EmergencyHaltedEvent.OutputObject
    >;

    "FeeUpdated(uint256)": TypedContractEvent<
      FeeUpdatedEvent.InputTuple,
      FeeUpdatedEvent.OutputTuple,
      FeeUpdatedEvent.OutputObject
    >;
    FeeUpdated: TypedContractEvent<
      FeeUpdatedEvent.InputTuple,
      FeeUpdatedEvent.OutputTuple,
      FeeUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "Resumed(address)": TypedContractEvent<
      ResumedEvent.InputTuple,
      ResumedEvent.OutputTuple,
      ResumedEvent.OutputObject
    >;
    Resumed: TypedContractEvent<
      ResumedEvent.InputTuple,
      ResumedEvent.OutputTuple,
      ResumedEvent.OutputObject
    >;

    "TokenMappingUpdated(uint256,address,address)": TypedContractEvent<
      TokenMappingUpdatedEvent.InputTuple,
      TokenMappingUpdatedEvent.OutputTuple,
      TokenMappingUpdatedEvent.OutputObject
    >;
    TokenMappingUpdated: TypedContractEvent<
      TokenMappingUpdatedEvent.InputTuple,
      TokenMappingUpdatedEvent.OutputTuple,
      TokenMappingUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
