[toolchain]
channel = "1.0.0"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 10000
timeout = 120

[[test.genesis]]
address = "Kuberna1111111111111111111111111111"
program = "target/deploy/kuberna_solana.so"

[test.validator]
url = "https://api.devnet.solana.com"
ledger = ".anchor/test-ledger"

[scripts]
test = "cargo test --manifest-path ./programs/Cargo.toml"
build = "cargo build --manifest-path ./programs/Cargo.toml --release"
deploy = "solana program deploy target/deploy/kuberna_solana.so --url https://api.devnet.solana.com"